github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/skool-video-downloader",
"https://serp.co/products/skool-video-downloader/reviews/",
"https://chromewebstore.google.com/detail/skool-video-downloader-by/nllaldlnaeddjgoaboodnelelhilpbli",
]
