github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://store.serp.co/product-details/product/skool-video-downloader",
"https://apps.serp.co/skool-video-downloader",
"https://serp.co/products/skool-video-downloader/reviews/",
"https://chromewebstore.google.com/detail/skool-video-downloader-by/nllaldlnaeddjgoaboodnelelhilpbli",
"https://whop.com/serp-downloaders/skool-video-downloader/"
]
