github: [devinschumacher]
liberapay: devinschumacher
open_collective: devinschumacher
custom: [
"https://serpapps.github.io/skool-downloader",
"https://devinschumacher.com/",
"https://downloadingfreevideo.com/how-to-download-skool-videos",
"https://serp.co/products/skool-video-downloader/reviews/",
]
